name: CI Pipeline
run-name: "Tests for ${{ github.event.pull_request.title || github.event.head_commit.message }}"

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - feat/*

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            suite: [unit, integration]
        name: Run ${{ matrix.suite }} tests
        steps:
            - uses: actions/checkout@v5
            
            - uses: actions/setup-node@v6
              with:
                node-version: 24
                cache: npm
                cache-dependency-path: ./api/package-lock.json

            - working-directory: ./api
              run: npm ci
            
            - working-directory: ./api
              env:
                API_PORT: ${{ env.API_PORT }}
              run: npm run test:${{ matrix.suite }}